[package]
name = "suri-local"
version = "0.1.0"
edition = "2021"

[dependencies]
suri = { version = "0.2.3", registry = "nexcode" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
